name: Labeling new issue
on:
  issues:
      types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.1.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

enable: 
  issues: true 
  
labels: 
  'AnVIL':
  include: '\bAnVIL?\b'
  'KidsFirst':
  include: '\bKids?\b'
  'CRDC':
  include: '\bCRDC?\b'
  'NHLBI':
  include: '\bNHLBI?\b'
  'dbGaP':
  include: '\bdbGaP?\b'
