name: Labeling new issue AnVIL
on:
  issues:
      types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.1.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

defaults: '{"AnVIL:["anvil"]}'
