on:
  schedule:
  - cron: */15 * * * *
name: Hourly Issue Closure
jobs:
  cycle-hourly-close:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hourly-issue-closure
      uses: bdougie/close-issues-based-on-label@master
      env:
        LABEL: notmovingforward
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
