name: Close issues with label

on:
  schedule:
  - cron: 0 * * * *
name: Weekly Issue Closure
jobs:
  cycle-hourly-close:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: weekly-issue-closure
      uses: bdougie/close-issues-based-on-label@master
      env:
        LABEL: notmovingforward
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
